name: "hello workflow"
on:
  push:
    branches:
     - master
jobs:
  greeting:     
  runs-on: ubuntu-latest
  steps:
    - name: "Say Hello World"
      run: echo "hello world"
    - name: "Test project"
      run:  |
       echo "How are you"
       echo "Am fine"  